### ISSUE TITLE
Cannot deploy CDK

### ISSUE THREAD

**Issue by codecrack3** [pahud/aws-cdk-eks-sample#13]
Hi. I was deploying a new eks cluster with your repos but I got an error message. How I can i do to fix this problem?
![image](https://user-images.githubusercontent.com/9525576/103631802-0abfa880-4f76-11eb-82f2-66ac16c8d357.png)

Thank you

**Comment by pahud** [comment]
what commands did you execute?

Basically you should just clone this repo and run `yarn install` and `cdk deploy` and it should work.

**Comment by codecrack3** [comment]
> what commands did you execute?
> 
> Basically you should just clone this repo and run `yarn install` and `cdk deploy` and it should work.

Hi. 
Thank your reply. I tried to reinstall the package and I passed it but I have received an error again. 

![image](https://user-images.githubusercontent.com/9525576/103634473-b0c0e200-4f79-11eb-8276-ae7220d1b47a.png)

**Comment by codecrack3** [comment]
Yeah, I tried to use the command  'cdk bootstrap --profile ' and I solved it. 
Thank you very much.
